---
title: 'Project 1: Exploratory Data Analysis'
author: "SDS348"
date: '2020-12-09'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Natlia Gastelo (ng22639)

#### Introduction (4 pts) Write a narrative introductory paragraph or two describing the datasets you have chosen, the variables they contain, how they were acquired, and why they are interesting to you. Expand on potential associations you may expect, if any.

```{R}

library(tidyverse)
cricket1 <-read_csv("~/cricket1.csv")
cricket2 <-read_csv("~/cricket2.csv")
glimpse(cricket1)
glimpse(cricket2)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(cluster)
```

*In my first dataset (cricket1) I have 4 variables and 76 observations. In my second dataset (cricket2) I have 4 varaibles. The tao data sets include chirps and jumps per hour of 76 different crickets and it also includes the  temp at which these observations were recorded and whether it was raining.I aquired my datasets from google after looking at different websites with datasets that loooked interesting. I found this dataset interesting because I.....I expect that there will be a positive correlation between the different numeric variables.*

#### Tidying: Rearranging Wide/Long (8 pts) Tidy the datasets (using the `tidyr` functions `pivot_longer`/`gather` and/or `pivot_wider`/`spread`).If you data sets are already tidy, be sure to use those functions somewhere else in your project. Document the process (describe in words what was done per the instructions)

*I used pivot longer later in the project to create a correlation heatmap of my numeric variables. I used pivot longer to get everything but the first column.*

#### Joining/Merging (8 pts) Join your datasets into one using a `dplyr` join function. If you have multiple observations on the joining variable in either dataset, fix this by collapsing via summarize. Discuss the process in words, including why you chose the join you did. Discuss which cases were dropped, if any, and potential problems with this

```{R}
cricket_joined <- full_join(cricket1,cricket2)
glimpse(cricket_joined)
```

*In the two datasets that I have there was two common numeric variables, therefore I decided to do a full_join by joining both datasets by those two common variables. There was not any rows or columns that were lost after joining the two datasets together.*

#### Wrangling (40 pts) Use all six core `dplyr` functions in the service of generating summary statistics (18 pts). Use mutate at least once to generate a variable that is a function of at least one other variable. Compute at least 10 summary statistics for using summarize and summarize with group_by (18 pts). Use at least 5 unique functions inside of summarize (e.g., mean, sd). At least 2 of these should group by a categorical variable. Create one by dichotomizing a numeric if necessary. If applicable, at least 1 of these should group by two categorical variables. Strongly encouraged to create a correlation matrix with `cor()` on your numeric variables. Summarize/discuss all results in no more than two paragraphs (4 pts)

```{R}
cricket_joined %>% filter(Rain=="Y")
cricket_joined %>% filter(Rain=="N")
cricket_joined %>% filter(Temp<=20 & Rain=="N")
cricket_joined %>% arrange(desc(`JumpPerHour`))
cricket_joined %>% arrange(PeopleWalkingBy)
cricket_joined %>% select(Temp, 'ChirpsPerHour', 'JumpPerHour')
cricket_joined %>% group_by(PeopleWalkingBy)
cricket_joined %>% mutate(Rain2=recode(Rain, Y="Yes", N="No"))
cricket_joined %>% summarize_all(n_distinct)
cricket_joined %>%  filter(Rain=="N") %>% filter(PeopleWalkingBy > 100 )

cricket_joined %>% summarize_all(sd)
cricket_joined %>% summarize_all(mean)
cricket_joined %>% summarize_all(var)
cricket_joined %>% summarize_all(min)
cricket_joined %>% summarize_all(max)
cricket_joined %>% filter(Temp > 16) %>% summarize(sd(ChirpsPerHour,na.rm=T)) %>% group_by(Rain="N")
cricket_joined %>% filter(Temp > 16) %>% summarize(mean(ChirpsPerHour,na.rm=T)) %>% group_by(Rain="N")
cricket_joined %>%  group_by(Rain=="N") %>% filter(PeopleWalkingBy > 100 ) %>% summarize(mean(JumpPerHour),na.rm=T)

cricket_joined %>% select(ChirpsPerHour,JumpPerHour) %>% cor %>% round(3)
cricket_joined %>% select(ChirpsPerHour,Temp) %>% cor %>% round(3)
cricket_joined %>% select(JumpPerHour,Temp) %>% cor %>% round(3)
```

*The standar deviation of chirps per hour when temperature is greater than 16 and rain is equal to "N" is 6.738. The mean value of chirps per hour when temperature is greater than 16 and rain is equal to "N" is 88.93. Lastly, the mean value of jumps per hour when rain is qual to "N" and people walking by is greater than 100 is 117.486. The correlation between chirps per hour and jumps per hour is -.992. The correlation between chirps per hour and temperature is .956. The correlation between jumps per hour and temperature is -.931. *

#### Visualizing (30 pts) Create a correlation heatmap of your numeric variables. Create two effective, polished plots with ggplot. Each plot should map 3+ variables to aesthetics. Each plot should have a title and clean labeling for all mappings. Change at least one default theme element and color for at least one mapping per plot. For at least one plot, add more tick marks (x, y, or both) than are given by default. For at least one plot, use the stat="summary" function. Supporting paragraph or two (for each plot) describing the relationships/trends that are apparent.

```{R}
ggplot(data = cricket_joined, aes(x = ChirpsPerHour, y = JumpPerHour)) + geom_point(color="Black") + geom_line(color="Purple")
ggplot(data = cricket_joined, aes(x = ChirpsPerHour, y = JumpPerHour)) + geom_point(size=4, aes(color = Temp))
ggplot(cricket_joined, aes(Temp))+ geom_bar(aes(y=JumpPerHour,fill=Rain), stat="summary", fun=mean) + theme(axis.text = element_text(size=14))

cricket_cor <- cricket_joined %>% select_if(is.numeric) %>% column_to_rownames(var="CricketNumber")
cricket_cor2 <- cricket_cor %>% cor
tidycor <- cricket_cor2 %>% as.data.frame %>% rownames_to_column("var1") %>%
  pivot_longer(-1,names_to="var2",values_to="correlation")

tidycor %>% ggplot(aes(var1,var2,fill=correlation)) + geom_tile() +
  scale_fill_gradient2(low="pink",mid="purple", high="white") + geom_text(aes(label=round(correlation,2)),color = "black", size = 4)+ #overlay values
  theme(axis.text.x = element_text(angle = 90, hjust=1))+ 
  coord_fixed() 
```

*By looking at my correlation heatmap we can clearly see that there is a positive correlation between chirps per hour and temperature.There is a highly negative corelation between jumps per hour and chirps per hour, as well as temperature and jump per hour. People walking by and jump per hour are slighly negatively correlated. People walking by and chirps per hour are slighly positviely correlated.* 

#### Dimensionality Reduction (20 pts) Either k-means/PAM clustering or PCA (inclusive "or") should be performed on at least three numeric variables in your dataset. All relevant steps discussed in class. A visualization of the clusters or the first few principal components (using ggplot2). Supporting paragraph or two describing results found 

```{R}
pam_dat<-cricket_joined%>%select(JumpPerHour,ChirpsPerHour)
sil_width<-vector()
for(i in 2:10){
  pam_fit <- pam(pam_dat, k = i)
  sil_width[i] <- pam_fit$silinfo$avg.width
}
ggplot()+geom_line(aes(x=1:10,y=sil_width))+scale_x_continuous(name="k",breaks=1:10)

#pam2 <-cricket_joined %>% select(-Rain) %>% select(-CricketNumber) %>% scale %>% pam(3)
#pam2
final <- cricket_joined %>% select(-Rain)  %>% select(-CricketNumber) %>%scale %>% as.data.frame
pam2 <- final %>% pam(3) 
final <- final %>% mutate(cluster=as.factor(pam2$clustering))
ggplot(final, aes(x=JumpPerHour,y=ChirpsPerHour, color=cluster))+geom_point()

library(GGally)

ggpairs(final, columns=1:4, aes(color=cluster))
plot(pam2, which=2)
```


*Distribution of cluster 3 is highest in all of the 4 different numberic variables.The overall correlation for chirps per hour and temp is highly correlated. Based on average sillhouette width =.37 we can say that the structure is weak and could be artificial.*


...


