---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "Natalia Gastelo SDS348"
date: '2020-12-09'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library(tidyverse)
```

# Modeling

## Instructions

A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(...) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)! 

Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)

## Find data:

Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (*at least* 10 observations for every explanatory variable you have, ideally 20+ observations/variable).

It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.

Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: https://vincentarelbundock.github.io/Rdatasets/datasets.html.


## Guidelines and Rubric

- **0. (5 pts)** Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?
```{R}
library(carData)
head(Salaries)
```
*The dataset contains information about salaries of professors, asst professors, and assoc prof. It gives us details about their discipline, levels A (``theoretical'' departments) or B (``applied'' departments), sex, years since PhD, and years of service.

- **1. (15 pts)** Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss MANOVA assumptions and whether or not they are likely to have been met (no need for anything too in-depth) (2).
```{R}
manova <- manova(cbind(yrs.since.phd,salary,yrs.service)~discipline,data=Salaries)
summary(manova)

summary.aov(manova)

pairwise.t.test(Salaries$yrs.since.phd, Salaries$discipline, p.adj="none")
pairwise.t.test(Salaries$yrs.service, Salaries$discipline, p.adj="none")
pairwise.t.test(Salaries$salary, Salaries$discipline, p.adj="none")

ggplot(Salaries, aes(x = yrs.since.phd, y = salary)) +
geom_point(alpha = .5) + facet_wrap(~discipline)
```
*A MANOVA was run to get the effect of discipline level on 5 variables. Of those five variables, three were significant. Pairwise t-tests were run on salary, yrs.since.phd, and yrs.service and there was a significant difference. There were seven tests run, which means that the probability of a type I error is 0.35. Therefore, the (alpha) needs to be adjusted. this would be (alpha = 0.05/7 = 0.0071\).*

- **2. (10 pts)** Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).
```{R}
mean(Salaries[Salaries$discipline=="A",]$salary)-
  mean(Salaries[Salaries$discipline=="B",]$salary)
#Randomization test
r_dist <- vector()
for(i in 1:5000){
  new<-data.frame(salary=sample(Salaries$salary), discipline=Salaries$discipline)
  r_dist[i]<-mean(new[new$discipline=="A",]$salary)- mean(new[new$discipline=="B",]$salary)}

#P-value
mean(r_dist>-9480.264)*2

{hist(r_dist, main="Randomized Distribution of Mean Differences", ylab="", 
      xlab="Difference Between Discipline A and B"); 
  abline(v=-9480.264, col="red")}
```
*The randomization test produced a p-value of 1.9976. This p-value tells us that there is not a significant difference in the salary between discipline A and discipline B.*

- **3. (35 pts)** Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.

    - Interpret the coefficient estimates (do not discuss significance) (10)
    - Plot the regression using `ggplot()` using geom_smooth(method="lm"). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the `interactions` package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (8)
    - Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)
    - Regardless, recompute regression results with robust standard errors via `coeftest(..., vcov=vcovHC(...))`. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)
    - What proportion of the variation in the outcome does your model explain? (4)
```{R}
Salaries$salary_c <- Salaries$salary-mean(Salaries$salary)
Salaries$yrs.since.phd_c <- Salaries$yrs.since.phd-mean(Salaries$salary)

part3 <- lm(salary_c ~ yrs.since.phd_c*discipline, data=Salaries)
summary(part3)

Salaries$discipline<-factor(Salaries$discipline,levels=c("A","B"),labels=c("A","B"))

ggplot(Salaries, aes(x=yrs.since.phd, y=salary))+geom_point(aes(color=discipline))+
  geom_smooth(method="lm", se=F, fullrange=T, aes(color=discipline))+ 
xlab("Yrs since phd")+ylab("Salary")+theme_classic()

resids<-part3$residuals

#Tests for normality
shapiro.test(resids)
library(lmtest)
bptest(part3)
library(sandwich)
coeftest(part3, vcov = vcovHC(part3))
summary(part3)$r.sq
```

- **4. (5 pts)** Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)
```{R}
sample_dist<-replicate(5000, {
  bootstrapped<-Salaries[sample(nrow(Salaries), replace=TRUE),]
  part4<-lm(yrs.since.phd_c ~ salary_c*discipline, data=bootstrapped)
  coef(part4)
})
sample_dist%>%t%>%as.data.frame%>%summarize_all(sd)
```


- **5. (25 pts)** Fit a logistic regression model predicting a binary variable (if you don't have one, make/get one) from at least two explanatory variables (interaction not necessary). 

    - Interpret coefficient estimates in context (10)
    - Report a confusion matrix for your logistic regression (2)
    - Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)
    - Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (3)
    - Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)
```{R}
part5<-glm(discipline~salary+yrs.since.phd+yrs.service, data=Salaries, family=binomial(link="logit"))
exp(coeftest(part5))

Salaries$prob<-predict(part5,type="response") 
Salaries$pred<-ifelse(Salaries$prob>0.5,"A","B")
#Confusion Matrix
table(prediction=as.numeric(Salaries$prob>.5),truth=Salaries$discipline)
#Accuracy 
(90+165)/397
#Sensitivity
165/216
#Specificity
90/181
#Recall 
165/256

Salaries$logpred<-predict(part5, type="link")
Salaries%>%ggplot()+geom_density(aes(logpred,color=discipline,fill=discipline), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+ggtitle("Density Plot of predicted A vs. B")+xlab("predictor (logit)")
```

- **6. (25 pts)** Perform a logistic regression predicting the same binary response variable from *ALL* of the rest of your variables (the more, the better!) 

    - Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)
    - Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)
    - Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., `lambda.1se`). Discuss which variables are retained. (5)
    - Perform 10-fold CV using only the variables lasso selected: compare model's out-of-sample AUC to that of your logistic regressions above (5)
```{R}
class_diagnostic <-function(probs,truth){
 tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
 acc=sum(diag(tab))/sum(tab)
 sens=tab[2,2]/colSums(tab)[2]
 spec=tab[1,1]/colSums(tab)[1]
 ppv=tab[2,2]/rowSums(tab)[2]
 if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
 
 ord<-order(probs, decreasing=TRUE)
 probs <- probs[ord]; truth <- truth[ord]
 TPR=cumsum(truth)/max(1,sum(truth))
 FPR=cumsum(!truth)/max(1,sum(!truth))
 dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
 TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
 n <- length(TPR)
 auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
 data.frame(acc,sens,spec,ppv,auc)
} 
set.seed(307)
k=10 

data1 <-Salaries[sample(nrow(Salaries)),]
folds<-cut(seq(1:nrow(Salaries)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
 train<-data1[folds!=i,]
 test<-data1[folds==i,]
 truth<-test$discipline
 fit<-glm(discipline~salary+yrs.since.phd+yrs.service, data=train, family=binomial(link="logit"))
 probs<-predict(fit,newdata = test,type="response")
 diags<-rbind(diags,class_diagnostic(probs,truth))
}
apply(diags,2,mean)

part6<-glm(discipline~yrs.since.phd+salary+yrs.service, data=Salaries, family=binomial(link="logit"))
coeftest(part6)
set.seed(307)
k=10 
data1<-Salaries[sample(nrow(Salaries)),]
folds<-cut(seq(1:nrow(Salaries)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
 train<-data1[folds!=i,]
 test<-data1[folds==i,]
 truth<-test$discipline
 fit <-glm(discipline~yrs.since.phd+salary, data=train, family=binomial(link="logit"))
 probs<-predict(fit,newdata = test,type="response")
 diags<-rbind(diags,class_diagnostic(probs,truth))
}

apply(diags,2,mean)
```
...





